version: "3"
services:
  pihole:
    cap_add:
      - ALL
    image: pihole/pihole:latest
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      # enter your docker host IP here
      ServerIP: 192.168.1.33
      # IPv6 Address if your network supports it
      #ServerIPv6: 192.168.1.55
      # jwilder/proxy envs, see readme for more info
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: pihole.canferalv.local
      VIRTUAL_PORT: 80
      TZ: "Europe/Madrid"
      DNS1: 1.1.1.1
      DNS2: 1.0.0.1
    # Add your own custom hostnames you need for your domain
    extra_hosts:
      #   Point any of the jwilder virtual_host addresses
      # to your docker host ip address
      - 'pihole.canferalv.local:192.168.1.33'
      - 'bradipo.canferalv.local:192.168.1.33'
      - 'salotto.canferalv.local:192.168.1.34'
      - 'router.canferalv.local:192.168.1.1'
    volumes:
      - '/etc/pihole/:/etc/pihole/'
      # WARNING: if this log don't exist as a file on the host already
      # docker will try to create a directory in it's place making for lots of errors
      - '/var/log/pihole.log:/var/log/pihole.log'
    restart: always
